name: Pre-Publish Verification Hook

on:
  workflow_call:
    inputs:
      image_digest:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  verify:
    name: Cryptographic & Vulnerability Verification
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 #v4.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 #v4.1.0

      - name: Verify Cosign Signature
        run: |
          cosign verify \
            --certificate-identity-regexp "https://github.com/.*" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ inputs.image_digest }}"

      - name: Verify Attestation Signatures
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh attestation verify "oci://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ inputs.image_digest }}" \
            --owner "${{ github.repository_owner }}"

    